added support for 128-bit MURMUR3 variant
logstash-plugins/logstash-filter-fingerprint pull request #66
Opened 2022-04-15 15:41 UTC by mmguero

As #42 hasn't been updated in some years, this PR takes the commit from that one and makes the following additions. This resolves #32 (at least as far as it applies to murmur3).

* modifies the CHANGELOG as requested by @kaisecheng
* changes the version number as requested by @kaisecheng
* adds tests as requested by @kaisecheng
* honors the convention of default hex-encoded vs. `base64encode` fingerprint representations (since unlike the 32-bit variant which just produces an integer the 128-bit functions in the [murmurhash3-ruby](https://github.com/funny-falcon/murmurhash3-ruby) library return an array of integers)

I'm running some more tests and whatnot now but I think this is ready for review.

2022-04-15 15:45 UTC, mmguero commented
Hmmm some build issues apparently, will resolve.

2022-04-15 15:53 UTC, mmguero commented
> Please, read and sign the above mentioned agreement if you want to contribute to this project

I have signed the CLA now

2022-04-15 15:57 UTC, mmguero commented
So as far as the failing tests go, the test is failing on the `@timestamp` fingerprinting, but only for ES v8+. Additionally, it isn't only failing for my changes but also for openssl and murmur3 32-bit, which I did not change. So I think there may be an issue with your test there.

2022-05-03 15:41 UTC, kaisecheng requested changes
@mmguero Awesome contribution! Good test coverage.
Thanks for taking the time to enhance the feature. I left a suggestion for variable name and doc improvement. We need `'logstash-mixin-ecs_compatibility_support', '~>1.2'` for backward compatibility.
The test failed in Logstash 8 because of the breaking change of Logstash::Timestamp. I will make a follow up PR to fix CI. No worries for the red.

2022-05-03 15:41 UTC, kaisecheng commented on CHANGELOG.md
> +  - [DOC] Added support for 128bit murmur variant [#66](https://github.com/logstash-plugins/logstash-filter-fingerprint/issues/66) (resolves [#32](https://github.com/logstash-plugins/logstash-filter-
```suggestion
  - Added support for 128bit murmur variant [#66](https://github.com/logstash-plugins/logstash-filter-fingerprint/pull/66).
```

2022-05-03 15:41 UTC, kaisecheng commented on lib/logstash/filters/fingerprint.rb
> +  MAX_32BIT = (1 << 31) - 1
suggestion: rename MAX_32BIT to INTEGER_MAX_32BIT

2022-05-03 15:41 UTC, kaisecheng commented on lib/logstash/filters/fingerprint.rb
> +  MIN_32BIT = -(1 << 31)
suggestion: rename MIN_32BIT to INTEGER_MIN_32BIT

2022-05-03 16:13 UTC, mmguero commented
Okay, I think I've made the changes you suggested. Thanks!

2022-05-03 16:53 UTC, kaisecheng approved these changes
LGTM 🎉 Great work!

2022-05-03 16:55 UTC, merged